var res = {
    HelloWorld_png: "res/HelloWorld.png",
    Over_png: "res/ASOverScene/over.png",
    Restart_normal_png: "res/ASOverScene/restart-normal.png",
    Restart_selected_png: "res/ASOverScene/restart-selected.png",
    Mainmenu_normal_png: "res/ASOverScene/mainmenu-normal.png",
    Mainmenu_selected_png: "res/ASOverScene/mainmenu-selected.png",
    Best_png: "res/ASOverScene/best.png",
    Current_png: "res/ASOverScene/current.png",
    Light_png: "res/ASOverScene/light.png",
    Gameover_png: "res/ASOverScene/gameover.png",
    ProgressBg_png: "res/Progress/progress_bg.png",
    Progress_1_png: "res/Progress/progress1.png",
    Progress_2_png: "res/Progress/progress2.png",
    Progress_3_png: "res/Progress/progress3.png",
    Alarm_clock1_png:"res/ASMainScene/alarm-clock1.png",
    Alarm_clock2_png:"res/ASMainScene/alarm-clock1.png",
    Alarm_clock3_png:"res/ASMainScene/alarm-clock3.png",
    MainBg_png: "res/ASMainScene/mainBg.png",
    StarMusic_mp3: "res/EffectAndMusic/startMusic.mp3",
    BgMain01_mp3: "res/EffectAndMusic/bgm01.mp3",
    BgMain02_mp3: "res/EffectAndMusic/bgm02.mp3",
    BgMain03_mp3: "res/EffectAndMusic/bgm03.mp3",
    BgMain04_mp3: "res/EffectAndMusic/bgm04.mp3",
    BgMain05_mp3: "res/EffectAndMusic/bgm05.mp3",
    BgMain06_mp3: "res/EffectAndMusic/bgm06.mp3",
    ScoreEffect_wav: "res/EffectAndMusic/scoreEffect.wav",
    Top_png:"res/ASMainScene/top.png",
    Bottom_png:"res/ASMainScene/bottom.png",
    Ready_png: "res/ASMainScene/ready.png",
    Go_png: "res/ASMainScene/Go!.png",
    TimeOver_png: "res/ASMainScene/timeover.png",
    Xiong01_png: "res/ASMainScene/xiong01.png",
    Xiong02_png: "res/ASMainScene/xiong02.png",
    Xiong03_png: "res/ASMainScene/xiong03.png",
    XiongOnclick01_png: "res/ASMainScene/xiongonclick01.png",
    XiongOnclick02_png: "res/ASMainScene/xiongonclick02.png",
    Qiqiu01_png: "res/ASMainScene/qiqiu01.png",
    Qiqiu02_png: "res/ASMainScene/qiqiu02.png",
    Qiqiu03_png: "res/ASMainScene/qiqiu03.png",
    Citun01_png: "res/ASMainScene/citun01.png",
    Citun02_png: "res/ASMainScene/citun02.png",
    Citun03_png: "res/ASMainScene/citun03.png",
    CitunOnclick01_png: "res/ASMainScene/citunonclick01.png",
    CitunOnclick02_png: "res/ASMainScene/citunonclick02.png",
    CitunOnclick03_png: "res/ASMainScene/citunonclick03.png",
    CitunOnclick04_png: "res/ASMainScene/citunonclick04.png",
    Tu01_png: "res/ASMainScene/tu01.png",
    Tu02_png: "res/ASMainScene/tu02.png",
    Tu03_png: "res/ASMainScene/tu03.png",
    TuOnclick01_png: "res/ASMainScene/tuonclick01.png",
    TuOnclick02_png: "res/ASMainScene/tuonclick02.png",
    YellowStar01_png:"res/ASMainScene/yellowStar-01.png",
    YellowStar02_png:"res/ASMainScene/yellowStar-02.png",
    YellowStar03_png:"res/ASMainScene/yellowStar-03.png",
    GreenStar01_png:"res/ASMainScene/greenStar-01.png",
    GreenStar02_png:"res/ASMainScene/greenStar-02.png",
    GreenStar03_png:"res/ASMainScene/greenStar-03.png",
    PurpleStar01_png:"res/ASMainScene/purpleStar-01.png",
    PurpleStar02_png:"res/ASMainScene/purpleStar-02.png",
    PurpleStar03_png:"res/ASMainScene/purpleStar-03.png",
    Xin_png: "res/ASMainScene/xin.png",
    Point_png: "res/ASMainScene/point.png",
    Zanting_png: "res/ASMainScene/zanting.png",
    Jixu_png: "res/ASMainScene/jixu.png",
    Resume_normal_jpg: "res/ASMainScene/resume-normal.png",
    Resume_selected_jpg: "res/ASMainScene/resume-selected.png",
    Exit_normal_png: "res/ASMainScene/exit-normal.png",
    Exit_selected_png: "res/ASMainScene/exit-selected.png",
    Tanchu_png:"res/ASMainScene/tanchu.png",
    MaoOnclick_wav: "res/EffectAndMusic/maoOnclick.wav",
    ZhangOnclick_wav: "res/EffectAndMusic/zhangOnclick.wav",
    Ready_wav: "res/EffectAndMusic/ready.wav",
    Go_wav: "res/EffectAndMusic/go.wav",
    FirstStar_wav: "res/EffectAndMusic/firstStar.wav",
    SecondStar_wav: "res/EffectAndMusic/secondStar.wav",
    ThirdStar_wav: "res/EffectAndMusic/thirdStar.wav",
    TimeOver_wav: "res/EffectAndMusic/timeOver.wav",
    Grade1_wav:"res/EffectAndMusic/grade1.wav",
    Grade2_wav:"res/EffectAndMusic/grade2.wav",
    Grade3_wav:"res/EffectAndMusic/grade3.wav",
    StartBg_png:"res/ASStartScene/startBg.png",
    About_us_png:"res/ASStartScene/aboutus.png",
    Logo_png: "res/ASStartScene/logo.png",
    Start_normal_png: "res/ASStartScene/start-normal.png",
    Start_selected_png: "res/ASStartScene/start-selected.png",
    About_us_normal_png:"res/ASStartScene/aboutus-normal.png",
    About_us_selected_png:"res/ASStartScene/aboutus-selected.png",
    Music_off_normal_png: "res/ASStartScene/music-off-normal.png",
    Music_off_selected_png: "res/ASStartScene/music-off-selected.png",
    Music_on_normal_png: "res/ASStartScene/music-on-normal.png",
    Music_on_selected_png: "res/ASStartScene/music-on-selected.png",
    Effect_on_normal_png: "res/ASStartScene/effect-on-normal.png",
    Effect_on_selected_png: "res/ASStartScene/effect-on-selected.png",
    Effect_off_normal_png: "res/ASStartScene/effect-off-normal.png",
    Effect_off_selected_png: "res/ASStartScene/effect-off-selected.png",

};

var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}
